/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTablesRouteImport } from './routes/app.tables'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStockManagementRouteImport } from './routes/app.stock-management'
import { Route as AppStationsRouteImport } from './routes/app.stations'
import { Route as AppStaffSalesRouteImport } from './routes/app.staff-sales'
import { Route as AppStaffConsumptionRouteImport } from './routes/app.staff-consumption'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReservationsRouteImport } from './routes/app.reservations'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppQrScannerRouteImport } from './routes/app.qr-scanner'
import { Route as AppPrinterSettingsRouteImport } from './routes/app.printer-settings'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppKdsHistoryRouteImport } from './routes/app.kds-history'
import { Route as AppKdsRouteImport } from './routes/app.kds'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppDigitalMenuRouteImport } from './routes/app.digital-menu'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCateringRouteImport } from './routes/app.catering'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockManagementRoute = AppStockManagementRouteImport.update({
  id: '/stock-management',
  path: '/stock-management',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsRoute = AppStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffSalesRoute = AppStaffSalesRouteImport.update({
  id: '/staff-sales',
  path: '/staff-sales',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffConsumptionRoute = AppStaffConsumptionRouteImport.update({
  id: '/staff-consumption',
  path: '/staff-consumption',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppQrScannerRoute = AppQrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppPrinterSettingsRoute = AppPrinterSettingsRouteImport.update({
  id: '/printer-settings',
  path: '/printer-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsHistoryRoute = AppKdsHistoryRouteImport.update({
  id: '/kds-history',
  path: '/kds-history',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsRoute = AppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalMenuRoute = AppDigitalMenuRouteImport.update({
  id: '/digital-menu',
  path: '/digital-menu',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCateringRoute = AppCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/catering': typeof AppCateringRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/digital-menu': typeof AppDigitalMenuRoute
  '/app/events': typeof AppEventsRoute
  '/app/kds': typeof AppKdsRoute
  '/app/kds-history': typeof AppKdsHistoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer-settings': typeof AppPrinterSettingsRoute
  '/app/qr-scanner': typeof AppQrScannerRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/staff-consumption': typeof AppStaffConsumptionRoute
  '/app/staff-sales': typeof AppStaffSalesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/stock-management': typeof AppStockManagementRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tables': typeof AppTablesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/catering': typeof AppCateringRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/digital-menu': typeof AppDigitalMenuRoute
  '/app/events': typeof AppEventsRoute
  '/app/kds': typeof AppKdsRoute
  '/app/kds-history': typeof AppKdsHistoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer-settings': typeof AppPrinterSettingsRoute
  '/app/qr-scanner': typeof AppQrScannerRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/staff-consumption': typeof AppStaffConsumptionRoute
  '/app/staff-sales': typeof AppStaffSalesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/stock-management': typeof AppStockManagementRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tables': typeof AppTablesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/catering': typeof AppCateringRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/digital-menu': typeof AppDigitalMenuRoute
  '/app/events': typeof AppEventsRoute
  '/app/kds': typeof AppKdsRoute
  '/app/kds-history': typeof AppKdsHistoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer-settings': typeof AppPrinterSettingsRoute
  '/app/qr-scanner': typeof AppQrScannerRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/staff-consumption': typeof AppStaffConsumptionRoute
  '/app/staff-sales': typeof AppStaffSalesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/stock-management': typeof AppStockManagementRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tables': typeof AppTablesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/guest'
    | '/login'
    | '/app/catering'
    | '/app/customers'
    | '/app/digital-menu'
    | '/app/events'
    | '/app/kds'
    | '/app/kds-history'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos'
    | '/app/printer-settings'
    | '/app/qr-scanner'
    | '/app/receipts'
    | '/app/reports'
    | '/app/reservations'
    | '/app/settings'
    | '/app/staff'
    | '/app/staff-consumption'
    | '/app/staff-sales'
    | '/app/stations'
    | '/app/stock-management'
    | '/app/suppliers'
    | '/app/tables'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/login'
    | '/app/catering'
    | '/app/customers'
    | '/app/digital-menu'
    | '/app/events'
    | '/app/kds'
    | '/app/kds-history'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos'
    | '/app/printer-settings'
    | '/app/qr-scanner'
    | '/app/receipts'
    | '/app/reports'
    | '/app/reservations'
    | '/app/settings'
    | '/app/staff'
    | '/app/staff-consumption'
    | '/app/staff-sales'
    | '/app/stations'
    | '/app/stock-management'
    | '/app/suppliers'
    | '/app/tables'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/guest'
    | '/login'
    | '/app/catering'
    | '/app/customers'
    | '/app/digital-menu'
    | '/app/events'
    | '/app/kds'
    | '/app/kds-history'
    | '/app/menu'
    | '/app/notifications'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos'
    | '/app/printer-settings'
    | '/app/qr-scanner'
    | '/app/receipts'
    | '/app/reports'
    | '/app/reservations'
    | '/app/settings'
    | '/app/staff'
    | '/app/staff-consumption'
    | '/app/staff-sales'
    | '/app/stations'
    | '/app/stock-management'
    | '/app/suppliers'
    | '/app/tables'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tables': {
      id: '/app/tables'
      path: '/tables'
      fullPath: '/app/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-management': {
      id: '/app/stock-management'
      path: '/stock-management'
      fullPath: '/app/stock-management'
      preLoaderRoute: typeof AppStockManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stations': {
      id: '/app/stations'
      path: '/stations'
      fullPath: '/app/stations'
      preLoaderRoute: typeof AppStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff-sales': {
      id: '/app/staff-sales'
      path: '/staff-sales'
      fullPath: '/app/staff-sales'
      preLoaderRoute: typeof AppStaffSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff-consumption': {
      id: '/app/staff-consumption'
      path: '/staff-consumption'
      fullPath: '/app/staff-consumption'
      preLoaderRoute: typeof AppStaffConsumptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qr-scanner': {
      id: '/app/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/app/qr-scanner'
      preLoaderRoute: typeof AppQrScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/printer-settings': {
      id: '/app/printer-settings'
      path: '/printer-settings'
      fullPath: '/app/printer-settings'
      preLoaderRoute: typeof AppPrinterSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kds-history': {
      id: '/app/kds-history'
      path: '/kds-history'
      fullPath: '/app/kds-history'
      preLoaderRoute: typeof AppKdsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kds': {
      id: '/app/kds'
      path: '/kds'
      fullPath: '/app/kds'
      preLoaderRoute: typeof AppKdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/digital-menu': {
      id: '/app/digital-menu'
      path: '/digital-menu'
      fullPath: '/app/digital-menu'
      preLoaderRoute: typeof AppDigitalMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catering': {
      id: '/app/catering'
      path: '/catering'
      fullPath: '/app/catering'
      preLoaderRoute: typeof AppCateringRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCateringRoute: typeof AppCateringRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDigitalMenuRoute: typeof AppDigitalMenuRoute
  AppEventsRoute: typeof AppEventsRoute
  AppKdsRoute: typeof AppKdsRoute
  AppKdsHistoryRoute: typeof AppKdsHistoryRoute
  AppMenuRoute: typeof AppMenuRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPosRoute: typeof AppPosRoute
  AppPrinterSettingsRoute: typeof AppPrinterSettingsRoute
  AppQrScannerRoute: typeof AppQrScannerRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStaffConsumptionRoute: typeof AppStaffConsumptionRoute
  AppStaffSalesRoute: typeof AppStaffSalesRoute
  AppStationsRoute: typeof AppStationsRoute
  AppStockManagementRoute: typeof AppStockManagementRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTablesRoute: typeof AppTablesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCateringRoute: AppCateringRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDigitalMenuRoute: AppDigitalMenuRoute,
  AppEventsRoute: AppEventsRoute,
  AppKdsRoute: AppKdsRoute,
  AppKdsHistoryRoute: AppKdsHistoryRoute,
  AppMenuRoute: AppMenuRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPosRoute: AppPosRoute,
  AppPrinterSettingsRoute: AppPrinterSettingsRoute,
  AppQrScannerRoute: AppQrScannerRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppStaffConsumptionRoute: AppStaffConsumptionRoute,
  AppStaffSalesRoute: AppStaffSalesRoute,
  AppStationsRoute: AppStationsRoute,
  AppStockManagementRoute: AppStockManagementRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTablesRoute: AppTablesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
